export const IS_USER_LOGGED = "IS_USER_LOGGED"
export const LOGIN_USER = "LOGIN_USER"

export const OPEN_AUTH_MODAL = "OPEN_AUTH_MODAL"
export const CLOSE_AUTH_MODAL = "CLOSE_AUTH_MODAL"

export const OPEN_PROFILE_MODAL = "OPEN_PROFILE_MODAL"
export const CLOSE_PROFILE_MODAL = "CLOSE_PROFILE_MODAL"
export const UPDATE_PROFILE = "UPDATE_PROFILE"

export const GET_SESSION_USER = "GET_SESSION_USER"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_CURRENT_USER = "GET_CURRENT_USER"

export const GET_USER_POSTS = "GET_USER_POSTS"
export const GET_ALL_POSTS = "GET_ALL_POSTS"

export const CREATE_POST = "CREATE_POST"
export const SEARCH_POST = "SEARCH_POST"
export const GET_CURRENT_POST = "GET_CURRENT_POST"
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE"

export const OPEN_MEDIA_MODAL = "OPEN_MEDIA_MODAL"
export const CLOSE_MEDIA_MODAL = "CLOSE_MEDIA_MODAL"

